markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: public
sass:
  style: expanded  # nested|expanded|compact|compressed
  deploy_style: expanded  # nested|expanded|compact|compressed
  compile_in_place: true
